# Generated by Django 5.2.8 on 2025-11-30 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название конкурса')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.CharField(blank=True, max_length=255, verbose_name='Категория')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('finished', 'Завершён')], default='draft', max_length=20, verbose_name='Статус')),
                ('rules_file', models.FileField(blank=True, null=True, upload_to='rules/', verbose_name='Файл с правилами (PDF)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Конкурс',
                'verbose_name_plural': 'Конкурсы',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО участника')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('school', models.CharField(blank=True, max_length=255, verbose_name='Школа / колледж / вуз')),
                ('grade', models.CharField(blank=True, max_length=50, verbose_name='Класс / курс')),
                ('work_file', models.FileField(blank=True, null=True, upload_to='works/', verbose_name='Файл работы')),
                ('work_link', models.URLField(blank=True, verbose_name='Ссылка на работу')),
                ('status', models.CharField(choices=[('submitted', 'Подана'), ('under_review', 'На рассмотрении'), ('accepted', 'Принята'), ('rejected', 'Отклонена')], default='submitted', max_length=20, verbose_name='Статус заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='competitions.competition', verbose_name='Конкурс')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Баллы')),
                ('place', models.PositiveIntegerField(blank=True, null=True, verbose_name='Место')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий жюри')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='competitions.application', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
                'ordering': ['place', '-score'],
            },
        ),
    ]
